name: Build and Test Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PoolGame.WebAPI/PoolGame.WebAPI.csproj

      - name: Build project
        run: dotnet build PoolGame.WebAPI/PoolGame.WebAPI.csproj --configuration Release --no-restore

      

      - name: Build Docker image
        run: docker build -t poolgame-api:latest -f PoolGame.WebAPI/Dockerfile .

      # Optional: Push Docker image (see next step)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag poolgame-api:latest rishaviq/poolgame-api:latest

      - name: Push Docker image
        run: docker push rishaviq/poolgame-api:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull rishaviq/poolgame-api:latest
            docker stop poolgame-api || true
            docker rm poolgame-api || true
            docker run -d --name poolgame-api -p 5002:8080 \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
              -e JWT_AUDIENCE="${{ secrets.JWT_AUDIENCE }}" \
              -e JWT_EXPIRATION_MINUTES="${{ secrets.JWT_EXPIRATIONINMINUTES }}" \
              -e SQL_CONNECTION="${{ secrets.SQL_CONNECTION }}" \
              your-dockerhub-username/poolgame-api:latest